name: CD Dev AWS Account

on:
  push:
    branches:
      - main

jobs:
  download-artifacts:
    name: Download Artifacts
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      id-token: write
      packages: read
      pull-requests: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Get run ID of "ci_dev" workflow
        id: get-run-id
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          OTHER_REPO="${{ github.repository }}"
          WF_NAME="CI"
          RUN_ID=`gh run --repo ${OTHER_REPO} list --workflow ${WF_NAME} --json databaseId --jq .[0].databaseId`
          echo "Detected latest run id of ${RUN_ID} for workflow ${WF_NAME}"
          echo "run-id=${RUN_ID}" >> "$GITHUB_OUTPUT"

      - name: Download artifact from "CI" workflow
        uses: actions/download-artifact@v4
        with:
          name: layer
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ steps.get-run-id.outputs.run-id }}

      - name: Show downloaded files
        run: ls -la
