name: CI

on:
  pull_request:
    types: [opened, edited, synchronize, ready_for_review]
    branches:
      - main

jobs:
  create-artifacts:
    name: Create Artifacts
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      id-token: write
      packages: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install aws-xray-sdk
        run: |
          pip3 install aws-xray-sdk -t ./python
      
      - name: Zip aws-xray-sdk
        run: |
          zip -r layer.zip ./python

      - name: Upload layer.zip artifact
        uses: actions/upload-artifact@v3
        with:
          name: layer
          path: ./layer.zip